"""Created user schema

Revision ID: 21b7ddfe5cdb
Revises: 
Create Date: 2022-07-09 13:51:03.916743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b7ddfe5cdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('password_salt', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lecture5'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='lecture5')
    # ### end Alembic commands ###
