"""Added unique constraint to user email and username

Revision ID: ddfa9979a8d3
Revises: 21b7ddfe5cdb
Create Date: 2022-07-09 14:03:15.345374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfa9979a8d3'
down_revision = '21b7ddfe5cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'], schema='lecture5')
    op.create_unique_constraint(None, 'user', ['username'], schema='lecture5')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='lecture5', type_='unique')
    op.drop_constraint(None, 'user', schema='lecture5', type_='unique')
    # ### end Alembic commands ###
