"""Moved tables to lecture3 schema

Revision ID: 92100c673bb2
Revises: 4827d8d81686
Create Date: 2022-07-06 11:45:39.288761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92100c673bb2'
down_revision = '4827d8d81686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books', schema = "public")
    op.drop_table('readers', schema = "public")
    op.create_table('readers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk', name = "readers_pkey"),
    schema='lecture3',
    )
    op.create_table('books',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reader_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_pk'], ['lecture3.readers.pk'], ),
    sa.PrimaryKeyConstraint('pk', name = "readers_pkey"),
    schema='lecture3'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers', schema='lecture3')
    op.drop_table('books', schema='lecture3')
    op.create_table('books',
    sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reader_pk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reader_pk'], ['readers.pk'], name='books_reader_pk_fkey'),
    sa.PrimaryKeyConstraint('pk', name='books_pkey'),
    schema = "public",
    )
    op.create_table('readers',
    sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pk', name='readers_pkey'),
    schema = "public",
    )
    # ### end Alembic commands ###
