"""Added reader object

Revision ID: f40ea6a36bb1
Revises: dd007dafced5
Create Date: 2022-07-05 11:09:49.447108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40ea6a36bb1'
down_revision = 'dd007dafced5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
