"""Initial revision

Revision ID: 27ab5bc9fb67
Revises: 
Create Date: 2022-08-18 17:42:21.275096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ab5bc9fb67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lecture6'
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lecture6'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['lecture6.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='lecture6'
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('complainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complainer_id'], ['lecture6.user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['lecture6.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lecture6'
    )
    engine = op.get_bind()
    metadata = sa.MetaData(bind = engine, schema = "lecture6")
    role = sa.Table("role", metadata, autoload_with = engine)
    status = sa.Table("status", metadata, autoload_with = engine)

    op.bulk_insert(
        role,
        [{"role": "complainer"}, {"role": "approver"}, {"role": "admin"}],
    )
    op.bulk_insert(
        status,
        [{"status": "pending"}, {"status": "approved"}, {"status": "rejected"}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint', schema='lecture6')
    op.drop_table('user', schema='lecture6')
    op.drop_table('status', schema='lecture6')
    op.drop_table('role', schema='lecture6')
    # ### end Alembic commands ###
