"""Expanded models

Revision ID: 15c7371057c2
Revises: 2548aa01a42b
Create Date: 2022-07-08 12:34:28.729202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c7371057c2'
down_revision = '2548aa01a42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_item', sa.Column('clothing_item_id', sa.Integer(), nullable=False), schema='lecture4')
    op.add_column('clothing_item', sa.Column('name', sa.String(length=255), nullable=False), schema='lecture4')
    op.add_column('clothing_item', sa.Column('photo_url', sa.String(length=255), nullable=False), schema='lecture4')
    op.add_column('clothing_item', sa.Column('created_on', sa.DateTime(), nullable=True), schema='lecture4')
    op.add_column('clothing_item', sa.Column('updated_on', sa.DateTime(), nullable=True), schema='lecture4')
    op.create_unique_constraint(None, 'clothing_item', ['name'], schema='lecture4')
    op.drop_constraint("clothing_item_pkey", "clothing_item", schema = "lecture4")
    op.create_primary_key(
        "clothing_item_pkey", "clothing_item", ["clothing_item_id"], schema = "lecture4"
    )
    op.drop_column('clothing_item', 'clothing_id', schema='lecture4')
    colourenum = sa.Enum('PINK', 'BLACK', 'WHITE', 'YELLOW', name='colourenum')
    colourenum.create(bind = op.get_bind())
    sizeenum = sa.Enum('XS', 'S', 'M', 'L', 'XL', name='sizeenum')
    sizeenum.create(bind = op.get_bind())
    op.drop_column("colour", "colour", schema = "lecture4")
    op.add_column('colour', 
               sa.Column('colour', sa.Enum('PINK', 'BLACK', 'WHITE', 'YELLOW', name='colourenum'), nullable=False),
               schema='lecture4')
    op.drop_column("size", "size", schema = "lecture4")
    op.alter_column('size',
               sa.Column("size", sa.Enum('XS', 'S', 'M', 'L', 'XL', name='sizeenum'),
               nullable=False),
               schema='lecture4')
    op.add_column('user', sa.Column('phone', sa.Text(), nullable=True), schema='lecture4')
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True), schema='lecture4')
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=True), schema='lecture4')
    op.create_table('basket',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['lecture4.user.user_id'], ),
    sa.PrimaryKeyConstraint('basket_id'),
    schema='lecture4'
    )
    op.create_table('basket_item',
    sa.Column('basket_item_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['lecture4.basket.basket_id'], ),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['lecture4.clothing_item.clothing_item_id'], ),
    sa.ForeignKeyConstraint(['colour_id'], ['lecture4.colour.colour_id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['lecture4.size.size_id'], ),
    sa.PrimaryKeyConstraint('basket_item_id'),
    schema='lecture4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_item', schema='lecture4')
    op.drop_table('basket', schema='lecture4')
    op.drop_column('user', 'updated_on', schema='lecture4')
    op.drop_column('user', 'created_on', schema='lecture4')
    op.drop_column('user', 'phone', schema='lecture4')
    op.alter_column('size', 'size',
               existing_type=sa.Enum('XS', 'S', 'M', 'L', 'XL', name='sizeenum'),
               type_=sa.VARCHAR(length=10),
               nullable=True,
               schema='lecture4')
    op.alter_column('colour', 'colour',
               existing_type=sa.Enum('PINK', 'BLACK', 'WHITE', 'YELLOW', name='colourenum'),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               schema='lecture4')
    op.add_column('clothing_item', sa.Column('clothing_id', sa.INTEGER(), server_default=sa.text("nextval('lecture4.clothing_item_clothing_id_seq'::regclass)"), autoincrement=True, nullable=False), schema='lecture4')
    op.drop_constraint(None, 'clothing_item', schema='lecture4', type_='unique')
    op.drop_column('clothing_item', 'updated_on', schema='lecture4')
    op.drop_column('clothing_item', 'created_on', schema='lecture4')
    op.drop_column('clothing_item', 'photo_url', schema='lecture4')
    op.drop_column('clothing_item', 'name', schema='lecture4')
    op.drop_column('clothing_item', 'clothing_item_id', schema='lecture4')
    sizeenum = sa.Enum(name = "sizeenum")
    sizeenum.drop(bind = get_bind())
    colourenum = sa.Enum(name = "colourenum")
    colourenum.drop(bind = get_bind())
    # ### end Alembic commands ###
