"""Changed password and salt to binary

Revision ID: 2548aa01a42b
Revises: 2d20d2599210
Create Date: 2022-07-07 12:28:53.744081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2548aa01a42b'
down_revision = '2d20d2599210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash', schema = "lecture4")
    op.drop_column('user', 'password_salt', schema = "lecture4")
    op.add_column('user', sa.Column('password_hash', sa.LargeBinary, nullable = False), schema =
    "lecture4")
    op.add_column('user', sa.Column('password_salt',sa.LargeBinary, nullable = False), schema =
    "lecture4")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash', schema = "lecture4")
    op.drop_column('user', 'password_salt', schema = "lecture4")
    op.add_column('user', sa.Column('password_hash', sa.String(32), nullable = False), schema =
    "lecture4")
    op.add_column('user', sa.Column('password_salt', sa.String(32), nullable = False), schema =
    "lecture4")
    # ### end Alembic commands ###
