"""Added user table

Revision ID: 2d20d2599210
Revises: 
Create Date: 2022-07-07 11:12:26.516566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d20d2599210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_item',
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('clothing_id'),
    schema='lecture4'
    )
    op.create_table('colour',
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('colour_id'),
    schema='lecture4'
    )
    op.create_table('size',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('size_id'),
    schema='lecture4'
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=32), nullable=False),
    sa.Column('password_salt', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    schema='lecture4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='lecture4')
    op.drop_table('size', schema='lecture4')
    op.drop_table('colour', schema='lecture4')
    op.drop_table('clothing_item', schema='lecture4')
    # ### end Alembic commands ###
