"""Added user.email field

Revision ID: 2d78e45714e5
Revises: 15c7371057c2
Create Date: 2022-07-08 14:12:27.659812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d78e45714e5'
down_revision = '15c7371057c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', name='sizeenum'), nullable=False), schema='lecture4')
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False), schema='lecture4')
    op.create_unique_constraint(None, 'user', ['email'], schema='lecture4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='lecture4', type_='unique')
    op.drop_column('user', 'email', schema='lecture4')
    op.drop_column('size', 'size', schema='lecture4')
    # ### end Alembic commands ###
